apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tftethbridge.fullname" . }}
  labels:
    {{- include "tftethbridge.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tftethbridge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tftethbridge.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tftethbridge.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{ if .Values.enable_bridge }}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # ports:
          #   - name: http
          #     containerPort: 80
          #     protocol: TCP
          env:
          - name: STELLAR_SECRET
            value: {{ .Values.stellar_secret }}
          - name: ETH_KEY
            value: {{ .Values.eth_key }}
          - name: CONTRACT_ADDRESS
            value: {{ .Values.contract_address }}
          - name: ETH_NETWORK
            value: {{ .Values.eth_network }}
          - name: BRIDGE_MASTER_ADDRESS
            value: {{ .Values.bridge_master_address }}
          - name: STELLAR_FEE_WALLET
            value: {{ .Values.stellar_fee_wallet }}
          - name: STELLAR_NETWORK
            value: {{ .Values.network }}
          - name: ETH_URL
            value: {{ .Values.eth_url }}
          - name: RESCAN_HEIGHT
            value: {{ .Values.rescan_height | quote }}
          - name: DEPOSIT_FEE
            value: {{ .Values.deposit_fee | quote }}
          args: [
            "--secret", "$(STELLAR_SECRET)",
            "--ethkey", "$(ETH_KEY)",
            "--ethnetwork", "$(ETH_NETWORK)",
            "--contract", "$(CONTRACT_ADDRESS)",
            "--master", "$(BRIDGE_MASTER_ADDRESS)",
            "--network","$(STELLAR_NETWORK)",
            "--ethurl", "$(ETH_URL)",
            {{ if .Values.is_follower }}
            "--follower=true",
            {{ end }}
            "--feewallet", "$(STELLAR_FEE_WALLET)",
            "--persistency", "/storage/node.json",
            "--rescanHeight", "$(RESCAN_HEIGHT)",
            "--depositFee", "$(DEPOSIT_FEE)"
          ]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/eth-bridge
            - name: tftethbridge-storage-{{ .Release.Name }}
              mountPath: /storage
        {{ end }}
      volumes:
        - name: tftethbridge-storage-{{ .Release.Name }}
          persistentVolumeClaim:
            claimName: {{if .Values.volume.existingpersistentVolumeClaim }} {{.Values.volume.existingpersistentVolumeClaim}} {{ else }} tftethbridge-volume-claim-{{ .Release.Name }} {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
